### ISSUE TITLE
wildcard_index_check

### ISSUE THREAD

**Issue by prajapati93** [AsFigo/pyslint#64]
**Guideline:**  _Is the use of wildcard index with associative array recommended?_
Using wildcard index [*] with an associative array is not recommended, because it can lead to issues and unintended behavior. Wildcard indices are typically used with dynamic arrays, but they should be avoided with associative arrays. An example of incorrect use of wildcard index:
`string names[*]; // cannot be used with foreach, find_index, ...`

**Solution:** _Always use their known keys to access their elements._
It's better to iterate over known keys, or to use conditional checks when working with associative arrays to ensure the access of valid element.
`string names[int];`

_Expected output when wildcard index used with associative array:_
![Capture](https://github.com/AsFigo/pyslint/assets/108526370/bf9dae64-785b-45e6-ae46-2a09dd84aa48)

**Comment by svenka3** [comment]
Done
