### ISSUE TITLE
New rule check: one_module_per_file

### ISSUE THREAD

**Issue by prajapati93** [AsFigo/pyslint#79]
### **New Rule check: Only one module per file**
Few reasons why is it recommended to have only one module definition per file:

- **Namespace Organization:** Handling namespaces and preventing conflicts is complex.
- **Tool Compatibility:** Some tools may not work well with multi-module files.
- **Recompilation Inefficiency:** Modifying one module requires recompiling the entire file.
- **Version Control Complexity:** Tracking changes at the module level is difficult.
- **Reuse Issues:** Reusing individual modules is cumbersome, often leading to code duplication.

_Additionally, some specific issues to have more than one module in a file:_

- **Ambiguity:** Compiler struggles when two modules share the same name, making it unclear which one is referenced.
- **Circular Dependencies:** Modules in the same file depending on each other can lead to compiler failures due to circular dependencies.
- **Hidden Side Effects:** Sharing variables or signals in the same file makes it hard to trace changes' origins, leading to potential issues.

Expected output if there is more than one module in a file:
![Capture](https://github.com/AsFigo/pyslint/assets/108526370/c6d03950-840a-42e3-a961-e43901a5c50b)

**Comment by svenka3** [comment]
Done, thanks @prajapati93
